name: Auto-merge Dependabot

on: pull_request

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: dependabot/fetch-metadata@v1
        id: metadata
        with:
          github-token: ${{ github.token }}

      - name: Enable auto-merge
        if: steps.metadata.outputs.update-type == 'version-update:semver-patch'
        run: gh pr merge --auto --rebase "$PR"
        env:
          PR: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ github.token }}
